# Generated by Django 3.1.7 on 2021-12-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('videoId', models.CharField(max_length=20)),
                ('publishedAt', models.DateTimeField()),
                ('channelId', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('channelTitle', models.CharField(max_length=20)),
                ('thumbnails', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
